name: Check vulnerable NuGet packages
on: [push, pull_request]  # Specify when the action should run, e.g., on push or pull request

jobs:
  check-vulnerable-nuget-packages:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Check vulnerable NuGet packages
      uses: elmahio/github-check-vulnerable-nuget-packages-action@v1
      with:
        project: 
